config = {
  
    armas = {


        -------------------------------------AK-------------------------------------------------------------------->>
        {iventoryItem = 34, imagem = 'files/weapons/ak/1.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '1'},
        {iventoryItem = 35, imagem = 'files/weapons/ak/2.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '2'},
        {iventoryItem = 36, imagem = 'files/weapons/ak/3.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '3'},
        {iventoryItem = 37, imagem = 'files/weapons/ak/4.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '4'},
        {iventoryItem = 38, imagem = 'files/weapons/ak/5.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '5'},
        {iventoryItem = 39, imagem = 'files/weapons/ak/6.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '6'},
        {iventoryItem = 40, imagem = 'files/weapons/ak/7.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '7'},
        {iventoryItem = 41, imagem = 'files/weapons/ak/8.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '8'},
        {iventoryItem = 42, imagem = 'files/weapons/ak/9.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '9'},
        {iventoryItem = 43, imagem = 'files/weapons/ak/10.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '10'},
        {iventoryItem = 44, imagem = 'files/weapons/ak/11.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '11'},
        {iventoryItem = 45, imagem = 'files/weapons/ak/12.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '12'},
        {iventoryItem = 46, imagem = 'files/weapons/ak/13.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '13'},
        {iventoryItem = 47, imagem = 'files/weapons/ak/14.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '14'},
        {iventoryItem = 48, imagem = 'files/weapons/ak/15.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '15'},
        {iventoryItem = 49, imagem = 'files/weapons/ak/16.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '16'},
        {iventoryItem = 50, imagem = 'files/weapons/ak/17.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '17'},
        {iventoryItem = 51, imagem = 'files/weapons/ak/18.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '18'},
        {iventoryItem = 52, imagem = 'files/weapons/ak/19.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '19'},
        {iventoryItem = 53, imagem = 'files/weapons/ak/20.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '20'},
        {iventoryItem = 54, imagem = 'files/weapons/ak/21.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '21'},
        {iventoryItem = 55, imagem = 'files/weapons/ak/22.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '22'},
        {iventoryItem = 56, imagem = 'files/weapons/ak/23.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '23'},
        {iventoryItem = 57, imagem = 'files/weapons/ak/24.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '24'},
        {iventoryItem = 58, imagem = 'files/weapons/ak/25.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '25'},
        {iventoryItem = 59, imagem = 'files/weapons/ak/26.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '26'},
        {iventoryItem = 60, imagem = 'files/weapons/ak/27.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '27'},
        {iventoryItem = 61, imagem = 'files/weapons/ak/28.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '28'},
        {iventoryItem = 62, imagem = 'files/weapons/ak/29.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '29'},
        {iventoryItem = 63, imagem = 'files/weapons/ak/30.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '30'},
        {iventoryItem = 64, imagem = 'files/weapons/ak/31.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '31'},
        {iventoryItem = 65, imagem = 'files/weapons/ak/32.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '32'},
        {iventoryItem = 66, imagem = 'files/weapons/ak/33.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '33'},
        {iventoryItem = 67, imagem = 'files/weapons/ak/34.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '34'},
        {iventoryItem = 68, imagem = 'files/weapons/ak/35.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = '35'},
        {iventoryItem = 69, imagem = 'files/weapons/ak/36.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '36'},
        {iventoryItem = 70, imagem = 'files/weapons/ak/37.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '37'},
        {iventoryItem = 71, imagem = 'files/weapons/ak/38.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '38'},
        {iventoryItem = 72, imagem = 'files/weapons/ak/39.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '39'},
        {iventoryItem = 73, imagem = 'files/weapons/ak/40.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '40'},
        {iventoryItem = 74, imagem = 'files/weapons/ak/41.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '41'},
        {iventoryItem = 75, imagem = 'files/weapons/ak/42.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '42'},
        {iventoryItem = 76, imagem = 'files/weapons/ak/43.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '43'},
        {iventoryItem = 77, imagem = 'files/weapons/ak/44.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '44'},
        {iventoryItem = 78, imagem = 'files/weapons/ak/45.bmp', idWeapon = 30, weaponName = 'ak', nameSkin = '45'},
       ---------------------------------------m4-------------------------------------------------------------------->>
       {iventoryItem = 79, imagem = 'files/weapons/m4/1.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '46'},
       {iventoryItem = 80, imagem = 'files/weapons/m4/2.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '47'},
       {iventoryItem = 81, imagem = 'files/weapons/m4/3.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '48'},
       {iventoryItem = 82, imagem = 'files/weapons/m4/4.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '49'},
       {iventoryItem = 83, imagem = 'files/weapons/m4/5.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '50'},
       {iventoryItem = 84, imagem = 'files/weapons/m4/6.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '51'},
       {iventoryItem = 85, imagem = 'files/weapons/m4/7.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '52'},
       {iventoryItem = 86, imagem = 'files/weapons/m4/8.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '53'},
       {iventoryItem = 87, imagem = 'files/weapons/m4/9.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =   '54'},
       {iventoryItem = 88, imagem = 'files/weapons/m4/10.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '55'},
       {iventoryItem = 89, imagem = 'files/weapons/m4/11.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '56'},
       {iventoryItem = 90, imagem = 'files/weapons/m4/12.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '57'},
       {iventoryItem = 91, imagem = 'files/weapons/m4/13.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '58'},
       {iventoryItem = 92, imagem = 'files/weapons/m4/14.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '59'},
       {iventoryItem = 93, imagem = 'files/weapons/m4/15.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '60'},
       {iventoryItem = 94, imagem = 'files/weapons/m4/16.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '61'},
       {iventoryItem = 95, imagem = 'files/weapons/m4/17.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '62'},
       {iventoryItem = 96, imagem = 'files/weapons/m4/18.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '63'},
       {iventoryItem = 97, imagem = 'files/weapons/m4/19.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '64'},
       {iventoryItem = 98, imagem = 'files/weapons/m4/20.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '65'},
       {iventoryItem = 99, imagem = 'files/weapons/m4/21.jpg', idWeapon = 31, weaponName = 'm4', nameSkin =  '66'},
       {iventoryItem = 100, imagem = 'files/weapons/m4/22.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = '67'},
       {iventoryItem = 101, imagem = 'files/weapons/m4/23.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = '68'},
       {iventoryItem = 102, imagem = 'files/weapons/m4/24.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = '69'},
       {iventoryItem = 103, imagem = 'files/weapons/m4/25.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = '70'},
       {iventoryItem = 104, imagem = 'files/weapons/m4/26.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = '71'},




       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/camuflada.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'camuflada'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/prototipe.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'prototipe'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/snow.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'snow'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/aquamarina.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'aquamarina'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/barbie.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'barbie'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/blue.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'blue'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/combustao.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'combustao'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/desordem.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'desordem'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/gold.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'gold'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/halloween.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'halloween'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/inexplorada.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'inexplorada'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/natal.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'natal'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/red.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'red'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/reddragon.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'reddragon'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/redline.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'redline'},
       -- {iventoryItem = 'uzi', imagem = 'files/weapons/uzi/ultra.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'ultra'},
       -- 
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/camuflada.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'camuflada'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/prototipe.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'prototipe'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/snow.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'snow'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/aquamarina.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'aquamarina'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/barbie.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'barbie'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/blue.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'blue'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/combustao.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'combustao'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/desordem.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'desordem'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/gold.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'gold'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/halloween.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'halloween'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/inexplorada.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'inexplorada'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/natal.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'natal'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/red.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'red'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/reddragon.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'reddragon'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/redline.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'redline'},
       -- {iventoryItem = 'mp5', imagem = 'files/weapons/mp5/ultra.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'ultra'},
--
       --{iventoryItem = 167, imagem = 'files/weapons/karambit/camuflada.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'camuflada'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/prototipe.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'prototipe'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/snow.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'snow'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/aquamarina.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'aquamarina'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/barbie.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'barbie'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/blue.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'blue'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/combustao.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'combustao'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/desordem.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'desordem'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/gold.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'gold'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/halloween.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'halloween'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/inexplorada.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'inexplorada'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/natal.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'natal'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/red.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'red'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/reddragon.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'reddragon'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/redline.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'redline'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/ultra.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'ultra'},
       --
       --

       --{iventoryItem = 'five', imagem = 'files/weapons/five/camuflada.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'camuflada'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/exercito.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'exercito'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/gold.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'gold'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/grafite.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'grafite'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/natal.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'natal'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/rosa.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'rosa'},
       --
       ---- news

       --{iventoryItem = 'ak', imagem = 'files/weapons/ak/padrao.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = 'padrao'},
       --{iventoryItem = 'ak', imagem = 'files/weapons/ak/danger.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = 'danger'},

       --{iventoryItem = 'm4', imagem = 'files/weapons/m4/padrao.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = 'padrao'},
       --{iventoryItem = 'm4', imagem = 'files/weapons/m4/danger.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = 'danger'},

       --{iventoryItem = 'mp5', imagem = 'files/weapons/mp5/padrao.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'padrao'},
       --{iventoryItem = 'mp5', imagem = 'files/weapons/mp5/danger.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'danger'},

       --{iventoryItem = 'five', imagem = 'files/weapons/five/padrao.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'padrao'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/danger.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'danger'},

       --{iventoryItem = 'uzi', imagem = 'files/weapons/uzi/padrao.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'padrao'},
       --{iventoryItem = 'uzi', imagem = 'files/weapons/uzi/danger.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'danger'},

       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/padrao.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'padrao'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/danger.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'danger'},

       --{iventoryItem = '167', imagem = 'files/weapons/ak/os1.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = 'os1'},
       --{iventoryItem = 'm4', imagem = 'files/weapons/m4/os1.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = 'os1'},
       ----{iventoryItem = 'mp5', imagem = 'files/weapons/mp5/os1.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'os1'},
       ----{iventoryItem = 'five', imagem = 'files/weapons/five/os1.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'os1'},
       ---{iventoryItem = 'uzi', imagem = 'files/weapons/uzi/os1.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'os1'},
       ---{iventoryItem = 'faca', imagem = 'files/weapons/karambit/os1.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'os1'},

       --{iventoryItem = 'ak', imagem = 'files/weapons/ak/ps1.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = 'ps1'},
       --{iventoryItem = 'm4', imagem = 'files/weapons/m4/ps1.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = 'ps1'},
       --{iventoryItem = 'mp5', imagem = 'files/weapons/mp5/ps1.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'ps1'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/ps1.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'ps1'},
       --{iventoryItem = 'uzi', imagem = 'files/weapons/uzi/ps1.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'ps1'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/ps1.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'ps1'},

       --{iventoryItem = 'ak', imagem = 'files/weapons/ak/ds1.jpg', idWeapon = 30, weaponName = 'ak', nameSkin = 'ds1'},
       --{iventoryItem = 'm4', imagem = 'files/weapons/m4/ds1.jpg', idWeapon = 31, weaponName = 'm4', nameSkin = 'ds1'},
       --{iventoryItem = 'mp5', imagem = 'files/weapons/mp5/ds1.jpg', idWeapon = 29, weaponName = 'mp5', nameSkin = 'ds1'},
       --{iventoryItem = 'five', imagem = 'files/weapons/five/ds1.jpg', idWeapon = 23, weaponName = 'five', nameSkin = 'ds1'},
       --{iventoryItem = 'uzi', imagem = 'files/weapons/uzi/ds1.jpg', idWeapon = 32, weaponName = 'uzi', nameSkin = 'ds1'},
       --{iventoryItem = 'faca', imagem = 'files/weapons/karambit/ds1.jpg', idWeapon = 4, weaponName = 'faca', nameSkin = 'ds1'},

    },
    notifyS = function (player, message, type)
        exports['guetto_notify']:showInfobox(player, type, message)
    end
}
