



-- PIROS = 214,76,69 #d64c45
-- SÁRGA = 214,175,66 #d6af42
-- ZÖLD = 116,179,71 #74b347
-- KÉK = 84,144,196 #5490c4

modelFlags = {
	["one_exhaust"] = "0x0",
	["double_exhaust"] = "0x2000",
}

vehicleHandlings = {

	[562] = { 

			["mass"] = 500,
            ["turnMass"] = 1000,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 50,
            ["tractionMultiplier"] = 1.3,
            ["tractionLoss"] = 1.2,
            ["tractionBias"] = 0.600, -- Resposta do carro no A | D
            ["numberOfGears"] = 6,
            ["maxVelocity"] = 270,
            ["engineAcceleration"] = 25,
            ["engineInertia"] = 60,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.0,
            ["suspensionLowerLimit"] = -0.12,
            ["suspensionAntiDiveMultiplier"] = 0.0,

        ["modelFlags"] = modelFlags["one_exhaust"],
    },

    [479] = { 

        ["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.4,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 300,
        ["engineAcceleration"] = 10,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.5,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

    ["modelFlags"] = modelFlags["one_exhaust"],
    },

	[411] = { 

		["mass"] = 1000,
		["turnMass"] = 3000,
		["dragCoeff"] = 1.2,
		["centerOfMass"] = { 0, -0.20, -0.5  },
		["percentSubmerged"] = 30,
		["tractionMultiplier"] = 1.5,
		["tractionLoss"] = 1.4,
		["tractionBias"] = 0.400, -- Resposta do carro no A | D
		["numberOfGears"] = 6,
		["maxVelocity"] = 270,
		["engineAcceleration"] = 20,
		["engineInertia"] = 20,
		["driveType"] = "awd",
		["engineType"] = "petrol",
		["brakeDeceleration"] = 20,
		["ABS"] = true,
		["steeringLock"] = 50,
		["headLight"] = 0,
		["tailLight"] = 1,
		["animGroup"] = 0,
		["suspensionUpperLimit"] = 0.0,
		["suspensionLowerLimit"] = -0.12,
		["suspensionAntiDiveMultiplier"] = 0.0,

        ["modelFlags"] = modelFlags["one_exhaust"],
    },

	[547] = { 

			["mass"] = 1000,
            ["turnMass"] = 3000,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 30,
            ["tractionMultiplier"] = 1.5,
            ["tractionLoss"] = 1.4,
            ["tractionBias"] = 0.400, -- Resposta do carro no A | D
            ["numberOfGears"] = 5,
            ["maxVelocity"] = 290,
            ["engineAcceleration"] = 20,
            ["engineInertia"] = 20,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.0,
            ["suspensionLowerLimit"] = -0.12,
            ["suspensionAntiDiveMultiplier"] = 0.0,


        ["modelFlags"] = modelFlags["one_exhaust"],
    },

	[580] = { 

			["mass"] = 1000,
			["turnMass"] = 3000,
			["dragCoeff"] = 1.2,
			["centerOfMass"] = { 0, -0.20, -0.5  },
			["percentSubmerged"] = 30,
			["tractionMultiplier"] = 1.5,
			["tractionLoss"] = 1.4,
			["tractionBias"] = 0.400, -- Resposta do carro no A | D
			["numberOfGears"] = 5,
			["maxVelocity"] = 290,
			["engineAcceleration"] = 20,
			["engineInertia"] = 20,
			["driveType"] = "awd",
			["engineType"] = "petrol",
			["brakeDeceleration"] = 20,
			["ABS"] = true,
			["steeringLock"] = 50,
			["headLight"] = 0,
			["tailLight"] = 1,
			["animGroup"] = 0,
			["suspensionUpperLimit"] = 0.0,
			["suspensionLowerLimit"] = -0.15,
			["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[541] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.600, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 260,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[562] = { 

			["mass"] = 500,
            ["turnMass"] = 1000,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 50,
            ["tractionMultiplier"] = 1.3,
            ["tractionLoss"] = 1.2,
            ["tractionBias"] = 0.600, -- Resposta do carro no A | D
            ["numberOfGears"] = 6,
            ["maxVelocity"] = 270,
            ["engineAcceleration"] = 25,
            ["engineInertia"] = 60,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.0,
            ["suspensionLowerLimit"] = -0.12,
            ["suspensionAntiDiveMultiplier"] = 0.0,


			["modelFlags"] = modelFlags["one_exhaust"],
	},

	[602] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 50,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.600, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[456] = { 

		["mass"] = 1000,
        ["turnMass"] = 1500,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 120,
        ["engineAcceleration"] = 10,
        ["engineInertia"] = 30,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 20,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[415] = { 

		["mass"] = 1000,
        ["turnMass"] = 1500,
        ["dragCoeff"] = 1.5,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[474] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 250,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[405] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 250,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[529] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 260,
        ["engineAcceleration"] = 22,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[527] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 1500,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 265,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[426] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 1900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 180,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.15,
        ["suspensionLowerLimit"] = -0.25,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[550] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 1900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = {0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 230,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[516] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 1900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = {0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 180,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[522] = { 
		
		["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 180,
        ["engineAcceleration"] = 50,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[461] = { 
		
		["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 150,
        ["engineAcceleration"] = 40,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[468] = { 
		
		["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 150,
        ["engineAcceleration"] = 40,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[462] = { 
		
		["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 3,
        ["maxVelocity"] = 100,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[458] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[404] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 16,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[400] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 40,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 180,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 10,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[604] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 40,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 180,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 10,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[496] = { 
		
        ["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 40,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 140,
        ["engineAcceleration"] = 8,
        ["engineInertia"] = 10,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[526] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 1200,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 160,
        ["engineAcceleration"] = 13,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[545] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 1200,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 125,
        ["engineAcceleration"] = 9,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[422] = { 
		
		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 190,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[419] = { 
		
		["mass"] = 1000,
        ["turnMass"] = 1200,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 160,
        ["engineAcceleration"] = 13,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[579] = { 
		
		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 210,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = false,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[507] = { 
		
		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 18,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[518] = { 
		
		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[551] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 190,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[561] = { 

		["mass"] = 500,
		["turnMass"] = 1000,
		["dragCoeff"] = 1.2,
		["centerOfMass"] = { 0, -0.20, -0.5  },
		["percentSubmerged"] = 30,
		["tractionMultiplier"] = 1.5,
		["tractionLoss"] = 1.4,
		["tractionBias"] = 0.400, -- Resposta do carro no A | D
		["numberOfGears"] = 6,
		["maxVelocity"] = 200,
		["engineAcceleration"] = 20,
		["engineInertia"] = 20,
		["driveType"] = "awd",
		["engineType"] = "petrol",
		["brakeDeceleration"] = 20,
		["ABS"] = true,
		["steeringLock"] = 50,
		["headLight"] = 0,
		["tailLight"] = 1,
		["animGroup"] = 0,
		["suspensionUpperLimit"] = 0.0,
		["suspensionLowerLimit"] = -0.12,
		["suspensionAntiDiveMultiplier"] = 0.0,


		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[566] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[429] = { 

		["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 50,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 260,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[523] = { 

		["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 180,
        ["engineAcceleration"] = 50,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[598] = { 

		["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[585] = { 

		["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[597] = { 

		["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

	[596] = { 

		["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.5,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

		["modelFlags"] = modelFlags["one_exhaust"],
	},

   
}