config = {
    ["Carros"] = {
        -- Carros Concesionaria --

        [411] = { -- (Handling base) 
            ["mass"] = 1000,
            ["turnMass"] = 3000,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 30,
            ["tractionMultiplier"] = 1,
            ["tractionLoss"] = 1.4,
            ["tractionBias"] = 0.400, -- Resposta do carro no A | D
            ["numberOfGears"] = 6,
            ["maxVelocity"] = 250,
            ["engineAcceleration"] = 30,
            ["engineInertia"] = 60,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.0,
            ["suspensionLowerLimit"] = -0.12,
            ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [466] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 250,
        ["engineAcceleration"] = 40,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

         },

        [467] = { -- (Handling base) 
        ["mass"] = 1000,
            ["turnMass"] = 3000,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 30,
            ["tractionMultiplier"] = 1,
            ["tractionLoss"] = 1.4,
            ["tractionBias"] = 0.400, -- Resposta do carro no A | D
            ["numberOfGears"] = 6,
            ["maxVelocity"] = 200,
            ["engineAcceleration"] = 35,
            ["engineInertia"] = 60,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.10,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.15,

    },

        [547] = { -- (Handling base) 
            ["mass"] = 1000,
            ["turnMass"] = 3000,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 30,
            ["tractionMultiplier"] = 1,
            ["tractionLoss"] = 1.4,
            ["tractionBias"] = 0.400, -- Resposta do carro no A | D
            ["numberOfGears"] = 5,
            ["maxVelocity"] = 200,
            ["engineAcceleration"] = 15,
            ["engineInertia"] = 20,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.0,
            ["suspensionLowerLimit"] = -0.12,
            ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [580] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 50,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.600, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [541] = { -- (Handling base) 
        ["mass"] = 1100,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, 0.10, -0.44  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 250,
        ["engineAcceleration"] = 35,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [562] = { -- (Handling base) 
            ["mass"] = 1100,
            ["turnMass"] = 1800,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 50,
            ["tractionMultiplier"] = 1.3,
            ["tractionLoss"] = 1.2,
            ["tractionBias"] = 0.500, -- Resposta do carro no A | D
            ["numberOfGears"] = 5,
            ["maxVelocity"] = 250,
            ["engineAcceleration"] = 35,
            ["engineInertia"] = 60,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.0,
            ["suspensionLowerLimit"] = -0.12,
            ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [602] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 50,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.600, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 250,
        ["engineAcceleration"] = 35,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [456] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1500,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 120,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 30,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 20,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        
        [415] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1500,
        ["dragCoeff"] = 1.5,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 35,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [474] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 300,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [405] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 250,
        ["engineAcceleration"] = 35,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [529] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [527] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 2500,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.550, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 250,
         ["engineAcceleration"] = 35,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [426] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 180,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.15,
        ["suspensionLowerLimit"] = -0.25,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },


        [550] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = {0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [540] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = {0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [516] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = {0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 180,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [522] = { -- (Handling base moto) 
        ["mass"] = 530,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 300,
        ["engineAcceleration"] = 19,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,

        },

        [461] = { -- (Handling base moto) 
        ["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 300,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,

        },

        [468] = { -- (Handling base moto) 
        ["mass"] = 430,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 390,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,

        },

        [462] = { -- (Handling base moto) 
        ["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 3,
        ["maxVelocity"] = 100,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,

        },

        
        [458] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [404] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [479] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.4,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 300,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.5,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [400] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1500,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        
        [604] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 40,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 180,
       ["engineAcceleration"] = 14,
        ["engineInertia"] = 10,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [496] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 40,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 140,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 10,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 30,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },
        
        [526] = { -- (Handling base)  MODIFICAR
        ["mass"] = 1000,
        ["turnMass"] = 1200,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 160,
        ["engineAcceleration"] = 13,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [545] = { -- (Handling base)  MODIFICAR
        ["mass"] = 1000,
        ["turnMass"] = 1200,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 125,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },


        [422] = { -- (Handling base)  MODIFICAR
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 190,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [419] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1200,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 160,
        ["engineAcceleration"] = 13,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [579] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.1,
        ["centerOfMass"] = { 0, -0.20, -0.5 },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = false,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [507] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [518] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 1500,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 150,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [551] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1.2,
        ["tractionLoss"] = 1.1,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 5,
        ["maxVelocity"] = 190,
         ["engineAcceleration"] = 14,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.2,
        ["suspensionLowerLimit"] = -0.15,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [561] = { -- (Handling base) 
            ["mass"] = 1500,
            ["turnMass"] = 2000,
            ["dragCoeff"] = 1.2,
            ["centerOfMass"] = { 0, -0.20, -0.5  },
            ["percentSubmerged"] = 30,
            ["tractionMultiplier"] = 1,
            ["tractionLoss"] = 1.4,
            ["tractionBias"] = 0.400, -- Resposta do carro no A | D
            ["numberOfGears"] = 6,
            ["maxVelocity"] = 200,
            ["engineAcceleration"] = 15,
            ["engineInertia"] = 20,
            ["driveType"] = "awd",
            ["engineType"] = "petrol",
            ["brakeDeceleration"] = 20,
            ["ABS"] = true,
            ["steeringLock"] = 50,
            ["headLight"] = 0,
            ["tailLight"] = 1,
            ["animGroup"] = 0,
            ["suspensionUpperLimit"] = 0.0,
            ["suspensionLowerLimit"] = -0.12,
            ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [566] = { -- (Handling base) 
        ["mass"] = 1500,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 15,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

         },

         [421] = { -- (Handling base) 
         ["mass"] = 1500,
         ["turnMass"] = 2000,
         ["dragCoeff"] = 1.2,
         ["centerOfMass"] = { 0, -0.20, -0.5  },
         ["percentSubmerged"] = 30,
         ["tractionMultiplier"] = 1,
         ["tractionLoss"] = 1.4,
         ["tractionBias"] = 0.400, -- Resposta do carro no A | D
         ["numberOfGears"] = 6,
         ["maxVelocity"] = 200,
         ["engineAcceleration"] = 15,
         ["engineInertia"] = 20,
         ["driveType"] = "awd",
         ["engineType"] = "petrol",
         ["brakeDeceleration"] = 20,
         ["ABS"] = true,
         ["steeringLock"] = 50,
         ["headLight"] = 0,
         ["tailLight"] = 1,
         ["animGroup"] = 0,
         ["suspensionUpperLimit"] = 0.0,
         ["suspensionLowerLimit"] = -0.12,
         ["suspensionAntiDiveMultiplier"] = 0.0,
 
          },


         [470] = { -- (Handling base) 
         ["mass"] = 1100,
         ["turnMass"] = 2000,
         ["dragCoeff"] = 1.2,
         ["centerOfMass"] = { 0, -0.20, -0.5  },
         ["percentSubmerged"] = 30,
         ["tractionMultiplier"] = 1,
         ["tractionLoss"] = 1.4,
         ["tractionBias"] = 0.400, -- Resposta do carro no A | D
         ["numberOfGears"] = 5,
         ["maxVelocity"] = 340,
         ["engineAcceleration"] = 15,
         ["engineInertia"] = 20,
         ["driveType"] = "awd",
         ["engineType"] = "petrol",
         ["brakeDeceleration"] = 20,
         ["ABS"] = true,
         ["steeringLock"] = 50,
         ["headLight"] = 0,
         ["tailLight"] = 1,
         ["animGroup"] = 0,
         ["suspensionUpperLimit"] = 0.0,
         ["suspensionLowerLimit"] = -0.12,
         ["suspensionAntiDiveMultiplier"] = 0.0,
 
          },

        [429] = { -- (Handling base) 
        ["mass"] = 500,
        ["turnMass"] = 1000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 50,
        ["tractionMultiplier"] = 1.3,
        ["tractionLoss"] = 1.2,
        ["tractionBias"] = 0.450, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 260,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 60,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [523] = { -- (Handling base moto) 
        ["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 350,
        ["engineAcceleration"] = 30,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,

        },

        [586] = { -- (Handling base moto) 
        ["mass"] = 730,
        ["turnMass"] = 310,
        ["dragCoeff"] = 2.7,
        ["centerOfMass"] = { 0, 0.10, -0.44 } ,
        ["percentSubmerged"] = 75,
        ["tractionMultiplier"] = 2.6,
        ["tractionLoss"] = 1.0,
        ["tractionBias"] = 0.477,
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 350,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 50,
        ["driveType"] = "rwd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 22,
        ["ABS"] = false,
        ["steeringLock"] = 40,
        ["headLight"] = 0,
        ["tailLight"] = 9,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.873,
        ["suspensionLowerLimit"] = -0.3,

        },

        [598] = { -- (Handling base) 
        ["mass"] = 1500,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [490] = { -- (Handling base) 
        ["mass"] = 1500,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },


        

        [585] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 20,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        
        [597] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 3000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.400, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 270,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },

        [596] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 2000,
        ["dragCoeff"] = 1.2,
        ["centerOfMass"] = { 0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.500, -- Resposta do carro no A | D
        ["numberOfGears"] = 6,
        ["maxVelocity"] = 290,
        ["engineAcceleration"] = 25,
        ["engineInertia"] = 20,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 20,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },
        
        [475] = { -- (Handling base) 
        ["mass"] = 1000,
        ["turnMass"] = 2900,
        ["dragCoeff"] = 1.3,
        ["centerOfMass"] = {0, -0.20, -0.5  },
        ["percentSubmerged"] = 30,
        ["tractionMultiplier"] = 1,
        ["tractionLoss"] = 1.4,
        ["tractionBias"] = 0.300, -- Resposta do carro no A | D
        ["numberOfGears"] = 4,
        ["maxVelocity"] = 200,
        ["engineAcceleration"] = 14,
        ["engineInertia"] = 30,
        ["driveType"] = "awd",
        ["engineType"] = "petrol",
        ["brakeDeceleration"] = 10,
        ["ABS"] = true,
        ["steeringLock"] = 50,
        ["headLight"] = 0,
        ["tailLight"] = 1,
        ["animGroup"] = 0,
        ["suspensionUpperLimit"] = 0.0,
        ["suspensionLowerLimit"] = -0.12,
        ["suspensionAntiDiveMultiplier"] = 0.0,

        },
  
  

    },


}